workspace = 1, persistent, monitor: HDMI-A-1, default = true
workspace = 2, persistent, monitor: DP-1, default = true
workspace = 3, persistent, monitor: DP-1
workspace = 5, monitor: HDMI-A-1
workspace = 9, persistent, monitor: HDMI-A-1
