# env variables
#env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,mango
env = XDG_SESSION_DESKTOP,mango
env = XDG_CURRENT_SESSION_TYPE,wayland
env = XDG_DESKTOP_PORTAL,mango
#env = SDL_VIDEODRIVER,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = GTK_USE_PORTAL,1

# Autostart applications
exec-once = noctalia
exec-once = easyeffects
exec-once = qpwgraph
exec-once = zen-beta
exec-once = steam
exec-once = vesktop
exec-once = ~/Documents/audioscript.sh

