# env variables
#env = XDG_CURRENT_DESKTOP,mango
#env = XDG_SESSION_DESKTOP,mango
#env = XDG_CURRENT_SESSION_TYPE,wayland
#env = XDG_DESKTOP_PORTAL,mango
##env = SDL_VIDEODRIVER,wayland
#env = ELECTRON_OZONE_PLATFORM_HINT,wayland
#env = GTK_USE_PORTAL,1
#env = QT_QPA_PLATFORM,wayland

# Autostart applications
exec_once = systemctl --user enable --now hyprpolkitagent.service
exec_once = noctalia
exec_once = easyeffects
exec_once = qpwgraph
exec_once = steam
exec_once = vesktop
exec_once = zen-beta
exec_once = ~/Documents/audioscript.sh
# why is this shit not working
exec_once = systemctl --user start xdg-desktop-portal.service --ignore-dependencies

