# env variables
env = XDG_CURRENT_DESKTOP,mango
env = XDG_SESSION_DESKTOP,mango
env = XDG_CURRENT_SESSION_TYPE,wayland
env = XDG_DESKTOP_PORTAL,mango
#env = SDL_VIDEODRIVER,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = GTK_USE_PORTAL,1
env = QT_QPA_PLATFORM,wayland

# Autostart applications
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = noctalia
exec-once = easyeffects
exec-once = qpwgraph
exec-once = steam
exec-once = vesktop
exec-once = zen-beta
exec-once = ~/Documents/audioscript.sh
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user restart xdg-desktop-portal.service xdg-desktop-portal-wlr.service
