source = ./monitors.conf
source = ./windowrules.conf
source = ./visuals.conf
source = ./misc.conf
source = ./tagrules.conf
source = ./inputdevices.conf
source = ./keybinds.conf
source = ./autostart.conf
exec-once = systemctl --user start xdg-desktop-portal.service --ignore-dependencies
