keymode = common
bind = SUPER, r, reload_config
bind = SUPER, d, setkeymode, default

keymode = default
bind = SUPER, Return, spawn, kitty 
bind = SUPER, Space, spawn, noctalia msg panel-toggle launcher 
bind = SUPER, z, spawn, zen-beta
bind = SUPER, e, spawn, kitty -T files -e yazi

bind=SUPER, s, spawn_shell, sh -c 'REGION=$(slurp) && f=~/Pictures/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png && grim -g "$REGION" - | tee "$f" | wl-copy && notify-send "Screenshot Captured" "Saved to $f"'

bind = SUPER+ALT, a, minimized
bind = SUPER, a, toggle_scratchpad
bind = SUPER+SHIFT, a, restore_minimized

#bind = SUPER, p, toggle_named_scratchpad, appid:io.github.alainm23.planify, none, io.github.alainm23.planify
bind = SUPER, p, spawn, ~/.dots/scripts/mangoscratch.sh -s 0.7 planify io.github.alainm23.planify
bind = SUPER, n, spawn, ~/.dots/scripts/mangoscratch.sh -s 0.8 nvim kitty -e nvim
bind = SUPER, o, spawn, ~/.dots/scripts/mangoscratch.sh -s 0.8 quicknote kitty -e nvim ~/Documents/Quicknotes/$(date +%Y-%m-%d_%H-%M-%S).txt -c 'Neotree ~/Documents/Quicknotes/'

bind = SUPER+CTRL, right, viewtoright
bind = SUPER+CTRL, left, viewtoleft

bind = SUPER+ALT, right, tagtoright
bind = SUPER+ALT, left, tagtoleft

bind = SUPER, right, focusdir, right
bind = SUPER, left, focusdir, left
bind = SUPER, down, focusdir, down
bind = SUPER, up, focusdir, up

bind = SUPER+SHIFT, right, focusmon, HDMI-A-1
bind = SUPER+SHIFT, left, focusmon, DP-1

bind = SUPER, 1, view, 1
bind = SUPER, 2, view, 2
bind = SUPER, 3, view, 3
bind = SUPER, 4, view, 4
bind = SUPER, 5, view, 5
bind = SUPER, 6, view, 6
bind = SUPER, 7, view, 7
bind = SUPER, 8, view, 8
bind = SUPER, 9, view, 9

bind = SUPER, q, killclient
bind = SUPER, w, togglefloating
bind = SUPER, f, togglefullscreen

mousebind = SUPER, btn_left, moveresize, curmove
mousebind = SUPER, btn_right, moveresize, curresize

