borderpx = 3
gappih = 4
gappiv = 4
gappoh = 7
gappov = 7

focuscolor = 0x9f40d655

#cursor_size = 24
#cursor_theme = Catppuccin-Mocha-Peach

blur = 1

border_radius = 6
focused_opacity = 0.95
unfocused_opacity = 0.9
