# windowrules

window_rule = app_id:steam, tags:1, monitor:DP-1
window_rule = app_id:vesktop, tags:1, monitor:HDMI-A-1
window_rule = app_id:obs, tags:2, monitor:HDMI-A-1
window_rule = app_id:easyeffects, tags:9, monitor:HDMI-A-1
window_rule = app_id:qpwgraph, tags:9, monitor:HDMI-A-1

window_rule = app_id:Celeste, monitor:DP-1, is_fullscreen:1
window_rule = app_id:Terraria.bin.x84_64, monitor:DP-1, is_fullscreen:1


window_rule_once = app_id:zen-beta, tags:2, monitor:DP-1
