# windowrules

windowrule = appid:steam, tags:1, monitor:DP-1, appid:steam
windowrule = appid:vesktop, tags:1, monitor:HDMI-A-1
#windowrule = appid:zen-beta, tags:2, monitor:DP-1
windowrule = appid:obs, tags:2, monitor:HDMI-A-1
windowrule = appid:easyeffects, tags:9, monitor:HDMI-A-1
windowrule = appid:qpwgraph, tags:9, monitor:HDMI-A-1

windowrule = appid:Celeste, monitor:DP-1, isfullscreen:1

windowrule = appid:file_chooser, isfloating:1
windowrule = appid:ueberzugpp.*, isfloating:1, isopensilent:1

